# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combo_box_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComboBoxDialog(object):
    def setupUi(self, ComboBoxDialog):
        ComboBoxDialog.setObjectName("ComboBoxDialog")
        ComboBoxDialog.resize(174, 67)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/galaxy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ComboBoxDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ComboBoxDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(ComboBoxDialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ComboBoxDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ComboBoxDialog)
        self.buttonBox.accepted.connect(ComboBoxDialog.accept)
        self.buttonBox.rejected.connect(ComboBoxDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ComboBoxDialog)

    def retranslateUi(self, ComboBoxDialog):
        _translate = QtCore.QCoreApplication.translate
        ComboBoxDialog.setWindowTitle(_translate("ComboBoxDialog", "Combo Box Dialog"))
import resources_rc
