# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_text_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTextWidget(object):
    def setupUi(self, EditTextWidget):
        EditTextWidget.setObjectName("EditTextWidget")
        EditTextWidget.resize(183, 223)
        self.gridLayout = QtWidgets.QGridLayout(EditTextWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.autoIndexBox = QtWidgets.QGroupBox(EditTextWidget)
        self.autoIndexBox.setEnabled(True)
        self.autoIndexBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.autoIndexBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.autoIndexBox.setCheckable(True)
        self.autoIndexBox.setObjectName("autoIndexBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.autoIndexBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.setIndexButton = QtWidgets.QPushButton(self.autoIndexBox)
        self.setIndexButton.setObjectName("setIndexButton")
        self.gridLayout_2.addWidget(self.setIndexButton, 0, 0, 1, 1)
        self.indexLabel = QtWidgets.QLabel(self.autoIndexBox)
        self.indexLabel.setObjectName("indexLabel")
        self.gridLayout_2.addWidget(self.indexLabel, 0, 1, 1, 2)
        self.decrementRadioButton = QtWidgets.QRadioButton(self.autoIndexBox)
        self.decrementRadioButton.setObjectName("decrementRadioButton")
        self.gridLayout_2.addWidget(self.decrementRadioButton, 1, 0, 1, 1)
        self.incrementRadioButton = QtWidgets.QRadioButton(self.autoIndexBox)
        self.incrementRadioButton.setChecked(True)
        self.incrementRadioButton.setObjectName("incrementRadioButton")
        self.gridLayout_2.addWidget(self.incrementRadioButton, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.autoIndexBox, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QPlainTextEdit(EditTextWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)

        self.retranslateUi(EditTextWidget)
        QtCore.QMetaObject.connectSlotsByName(EditTextWidget)

    def retranslateUi(self, EditTextWidget):
        _translate = QtCore.QCoreApplication.translate
        EditTextWidget.setWindowTitle(_translate("EditTextWidget", "Form"))
        self.autoIndexBox.setTitle(_translate("EditTextWidget", "Auto-indexing"))
        self.setIndexButton.setToolTip(_translate("EditTextWidget", "Select the index you want to increment in the text above.  Then click this button."))
        self.setIndexButton.setText(_translate("EditTextWidget", "Set index"))
        self.indexLabel.setText(_translate("EditTextWidget", ":"))
        self.decrementRadioButton.setText(_translate("EditTextWidget", "decrease"))
        self.incrementRadioButton.setText(_translate("EditTextWidget", "increase"))
        self.textEdit.setPlaceholderText(_translate("EditTextWidget", "Next text"))
