# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug_watch_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugWatchWidget(object):
    def setupUi(self, DebugWatchWidget):
        DebugWatchWidget.setObjectName("DebugWatchWidget")
        DebugWatchWidget.resize(997, 107)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DebugWatchWidget.sizePolicy().hasHeightForWidth())
        DebugWatchWidget.setSizePolicy(sizePolicy)
        DebugWatchWidget.setMaximumSize(QtCore.QSize(16777215, 1666666))
        DebugWatchWidget.setStyleSheet("")
        self.grid_layout = QtWidgets.QGridLayout(DebugWatchWidget)
        self.grid_layout.setContentsMargins(6, 6, 6, 6)
        self.grid_layout.setObjectName("grid_layout")
        self.trans_origin_check = QtWidgets.QCheckBox(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_origin_check.sizePolicy().hasHeightForWidth())
        self.trans_origin_check.setSizePolicy(sizePolicy)
        self.trans_origin_check.setMaximumSize(QtCore.QSize(150, 16777215))
        self.trans_origin_check.setChecked(True)
        self.trans_origin_check.setObjectName("trans_origin_check")
        self.grid_layout.addWidget(self.trans_origin_check, 0, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.grid_layout.addWidget(self.label_4, 1, 0, 1, 2)
        self.accepts_hover_events_check = QtWidgets.QCheckBox(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accepts_hover_events_check.sizePolicy().hasHeightForWidth())
        self.accepts_hover_events_check.setSizePolicy(sizePolicy)
        self.accepts_hover_events_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.accepts_hover_events_check.setObjectName("accepts_hover_events_check")
        self.grid_layout.addWidget(self.accepts_hover_events_check, 1, 3, 1, 1)
        self.filters_child_events_check = QtWidgets.QCheckBox(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filters_child_events_check.sizePolicy().hasHeightForWidth())
        self.filters_child_events_check.setSizePolicy(sizePolicy)
        self.filters_child_events_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filters_child_events_check.setObjectName("filters_child_events_check")
        self.grid_layout.addWidget(self.filters_child_events_check, 0, 3, 1, 1)
        self.object_name_line = QtWidgets.QLineEdit(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.object_name_line.sizePolicy().hasHeightForWidth())
        self.object_name_line.setSizePolicy(sizePolicy)
        self.object_name_line.setMaximumSize(QtCore.QSize(206, 16777215))
        self.object_name_line.setReadOnly(True)
        self.object_name_line.setObjectName("object_name_line")
        self.grid_layout.addWidget(self.object_name_line, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.grid_layout.addWidget(self.label_3, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem, 0, 11, 1, 1)
        self.python_id_line = QtWidgets.QLineEdit(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.python_id_line.sizePolicy().hasHeightForWidth())
        self.python_id_line.setSizePolicy(sizePolicy)
        self.python_id_line.setMaximumSize(QtCore.QSize(206, 16777215))
        self.python_id_line.setReadOnly(True)
        self.python_id_line.setObjectName("python_id_line")
        self.grid_layout.addWidget(self.python_id_line, 0, 2, 1, 1)
        self.trans_origin_set_button = QtWidgets.QPushButton(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_origin_set_button.sizePolicy().hasHeightForWidth())
        self.trans_origin_set_button.setSizePolicy(sizePolicy)
        self.trans_origin_set_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trans_origin_set_button.setObjectName("trans_origin_set_button")
        self.grid_layout.addWidget(self.trans_origin_set_button, 0, 9, 1, 1)
        self.bounding_rect_check = QtWidgets.QCheckBox(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bounding_rect_check.sizePolicy().hasHeightForWidth())
        self.bounding_rect_check.setSizePolicy(sizePolicy)
        self.bounding_rect_check.setMinimumSize(QtCore.QSize(100, 0))
        self.bounding_rect_check.setMaximumSize(QtCore.QSize(150, 16777215))
        self.bounding_rect_check.setChecked(True)
        self.bounding_rect_check.setObjectName("bounding_rect_check")
        self.grid_layout.addWidget(self.bounding_rect_check, 0, 6, 1, 1)
        self.position_check = QtWidgets.QCheckBox(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_check.sizePolicy().hasHeightForWidth())
        self.position_check.setSizePolicy(sizePolicy)
        self.position_check.setMaximumSize(QtCore.QSize(150, 16777215))
        self.position_check.setChecked(True)
        self.position_check.setObjectName("position_check")
        self.grid_layout.addWidget(self.position_check, 0, 4, 1, 1)
        self.itemBoundingRectSetButton = QtWidgets.QPushButton(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemBoundingRectSetButton.sizePolicy().hasHeightForWidth())
        self.itemBoundingRectSetButton.setSizePolicy(sizePolicy)
        self.itemBoundingRectSetButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.itemBoundingRectSetButton.setObjectName("itemBoundingRectSetButton")
        self.grid_layout.addWidget(self.itemBoundingRectSetButton, 0, 7, 1, 1)
        self.bounding_rect_line_spot = QtWidgets.QWidget(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bounding_rect_line_spot.sizePolicy().hasHeightForWidth())
        self.bounding_rect_line_spot.setSizePolicy(sizePolicy)
        self.bounding_rect_line_spot.setObjectName("bounding_rect_line_spot")
        self.grid_layout.addWidget(self.bounding_rect_line_spot, 1, 6, 1, 2)
        self.position_set_button = QtWidgets.QPushButton(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_set_button.sizePolicy().hasHeightForWidth())
        self.position_set_button.setSizePolicy(sizePolicy)
        self.position_set_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.position_set_button.setObjectName("position_set_button")
        self.grid_layout.addWidget(self.position_set_button, 0, 5, 1, 1)
        self.position_line_spot = QtWidgets.QWidget(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_line_spot.sizePolicy().hasHeightForWidth())
        self.position_line_spot.setSizePolicy(sizePolicy)
        self.position_line_spot.setObjectName("position_line_spot")
        self.grid_layout.addWidget(self.position_line_spot, 1, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_layout.addItem(spacerItem1, 2, 3, 1, 1)
        self.trans_origin_line_spot = QtWidgets.QWidget(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_origin_line_spot.sizePolicy().hasHeightForWidth())
        self.trans_origin_line_spot.setSizePolicy(sizePolicy)
        self.trans_origin_line_spot.setObjectName("trans_origin_line_spot")
        self.grid_layout.addWidget(self.trans_origin_line_spot, 1, 8, 1, 2)
        self.shape_check = QtWidgets.QCheckBox(DebugWatchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_check.sizePolicy().hasHeightForWidth())
        self.shape_check.setSizePolicy(sizePolicy)
        self.shape_check.setMaximumSize(QtCore.QSize(150, 16777215))
        self.shape_check.setObjectName("shape_check")
        self.grid_layout.addWidget(self.shape_check, 1, 11, 1, 1)

        self.retranslateUi(DebugWatchWidget)
        QtCore.QMetaObject.connectSlotsByName(DebugWatchWidget)

    def retranslateUi(self, DebugWatchWidget):
        _translate = QtCore.QCoreApplication.translate
        DebugWatchWidget.setWindowTitle(_translate("DebugWatchWidget", "Form"))
        self.trans_origin_check.setText(_translate("DebugWatchWidget", "transform. origin:"))
        self.label_4.setText(_translate("DebugWatchWidget", "PyQt item.objectName( ):"))
        self.accepts_hover_events_check.setText(_translate("DebugWatchWidget", "accepts hover events"))
        self.filters_child_events_check.setText(_translate("DebugWatchWidget", "filters child events"))
        self.label_3.setText(_translate("DebugWatchWidget", "Python id(item):"))
        self.trans_origin_set_button.setText(_translate("DebugWatchWidget", "set"))
        self.bounding_rect_check.setText(_translate("DebugWatchWidget", "bounding rect:"))
        self.position_check.setText(_translate("DebugWatchWidget", "position:"))
        self.itemBoundingRectSetButton.setText(_translate("DebugWatchWidget", "set"))
        self.position_set_button.setText(_translate("DebugWatchWidget", "set"))
        self.shape_check.setText(_translate("DebugWatchWidget", "shape"))


