# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugWidget(object):
    def setupUi(self, DebugWidget):
        DebugWidget.setObjectName("DebugWidget")
        DebugWidget.resize(1233, 198)
        DebugWidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(DebugWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(DebugWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tab_widget.setDocumentMode(True)
        self.tab_widget.setMovable(True)
        self.tab_widget.setTabBarAutoHide(True)
        self.tab_widget.setObjectName("tab_widget")
        self.watches_tab = QtWidgets.QWidget()
        self.watches_tab.setObjectName("watches_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.watches_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_parent_button = QtWidgets.QPushButton(self.watches_tab)
        self.add_parent_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_parent_button.sizePolicy().hasHeightForWidth())
        self.add_parent_button.setSizePolicy(sizePolicy)
        self.add_parent_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_parent_button.setObjectName("add_parent_button")
        self.gridLayout_2.addWidget(self.add_parent_button, 4, 4, 1, 1)
        self.refresh_rate_spin = QtWidgets.QSpinBox(self.watches_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_rate_spin.sizePolicy().hasHeightForWidth())
        self.refresh_rate_spin.setSizePolicy(sizePolicy)
        self.refresh_rate_spin.setAccelerated(True)
        self.refresh_rate_spin.setPrefix("")
        self.refresh_rate_spin.setMinimum(0)
        self.refresh_rate_spin.setMaximum(999999999)
        self.refresh_rate_spin.setProperty("value", 5)
        self.refresh_rate_spin.setObjectName("refresh_rate_spin")
        self.gridLayout_2.addWidget(self.refresh_rate_spin, 6, 4, 1, 1)
        self.add_children_button = QtWidgets.QPushButton(self.watches_tab)
        self.add_children_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_children_button.sizePolicy().hasHeightForWidth())
        self.add_children_button.setSizePolicy(sizePolicy)
        self.add_children_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_children_button.setObjectName("add_children_button")
        self.gridLayout_2.addWidget(self.add_children_button, 5, 4, 1, 1)
        self.pick_watch_button = QtWidgets.QPushButton(self.watches_tab)
        self.pick_watch_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pick_watch_button.sizePolicy().hasHeightForWidth())
        self.pick_watch_button.setSizePolicy(sizePolicy)
        self.pick_watch_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pick_watch_button.setObjectName("pick_watch_button")
        self.gridLayout_2.addWidget(self.pick_watch_button, 2, 4, 1, 1)
        self.item_watch_tabs = QtWidgets.QTabWidget(self.watches_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_watch_tabs.sizePolicy().hasHeightForWidth())
        self.item_watch_tabs.setSizePolicy(sizePolicy)
        self.item_watch_tabs.setStyleSheet("")
        self.item_watch_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.item_watch_tabs.setDocumentMode(True)
        self.item_watch_tabs.setTabsClosable(True)
        self.item_watch_tabs.setMovable(True)
        self.item_watch_tabs.setTabBarAutoHide(False)
        self.item_watch_tabs.setObjectName("item_watch_tabs")
        self.gridLayout_2.addWidget(self.item_watch_tabs, 0, 0, 7, 3)
        self.add_watch_button = QtWidgets.QPushButton(self.watches_tab)
        self.add_watch_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_watch_button.sizePolicy().hasHeightForWidth())
        self.add_watch_button.setSizePolicy(sizePolicy)
        self.add_watch_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_watch_button.setObjectName("add_watch_button")
        self.gridLayout_2.addWidget(self.add_watch_button, 3, 4, 1, 1)
        self.tab_widget.addTab(self.watches_tab, "")
        self.events_tab = QtWidgets.QWidget()
        self.events_tab.setObjectName("events_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.events_tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.eventsList = QtWidgets.QListWidget(self.events_tab)
        self.eventsList.setStyleSheet("")
        self.eventsList.setObjectName("eventsList")
        self.gridLayout_3.addWidget(self.eventsList, 0, 0, 1, 1)
        self.tab_widget.addTab(self.events_tab, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)

        self.retranslateUi(DebugWidget)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DebugWidget)

    def retranslateUi(self, DebugWidget):
        _translate = QtCore.QCoreApplication.translate
        DebugWidget.setWindowTitle(_translate("DebugWidget", "Form"))
        self.add_parent_button.setText(_translate("DebugWidget", "Add Parent of Tab"))
        self.refresh_rate_spin.setSuffix(_translate("DebugWidget", " ms refresh"))
        self.add_children_button.setText(_translate("DebugWidget", "Add Children of Tab"))
        self.pick_watch_button.setText(_translate("DebugWidget", "Pick Item"))
        self.add_watch_button.setText(_translate("DebugWidget", "Add Selected"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.watches_tab), _translate("DebugWidget", "Watches"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.events_tab), _translate("DebugWidget", "Events"))


