# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagram_listing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiagramListing(object):
    def setupUi(self, DiagramListing):
        DiagramListing.setObjectName("DiagramListing")
        DiagramListing.resize(385, 290)
        self.gridLayout = QtWidgets.QGridLayout(DiagramListing)
        self.gridLayout.setObjectName("gridLayout")
        self.editButton = QtWidgets.QPushButton(DiagramListing)
        self.editButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 0, 1, 1, 1)
        self.removeButton = QtWidgets.QPushButton(DiagramListing)
        self.removeButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 0, 2, 1, 1)
        self.diagramTitleLabel = QtWidgets.QLabel(DiagramListing)
        self.diagramTitleLabel.setObjectName("diagramTitleLabel")
        self.gridLayout.addWidget(self.diagramTitleLabel, 0, 0, 1, 1)

        self.retranslateUi(DiagramListing)
        QtCore.QMetaObject.connectSlotsByName(DiagramListing)

    def retranslateUi(self, DiagramListing):
        _translate = QtCore.QCoreApplication.translate
        DiagramListing.setWindowTitle(_translate("DiagramListing", "Form"))
        self.editButton.setText(_translate("DiagramListing", "Edit"))
        self.removeButton.setText(_translate("DiagramListing", "❌"))
        self.diagramTitleLabel.setText(_translate("DiagramListing", "<html><head/><body><p><span style=\" font-size:16pt;\">Diagram Title</span></p></body></html>"))
