# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'font_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FontDialog(object):
    def setupUi(self, FontDialog):
        FontDialog.setObjectName("FontDialog")
        FontDialog.resize(246, 116)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/galaxy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FontDialog.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(FontDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(FontDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fontComboBox = QtWidgets.QFontComboBox(FontDialog)
        self.fontComboBox.setObjectName("fontComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fontComboBox)
        self.fontSizeSpinBox = QtWidgets.QSpinBox(FontDialog)
        self.fontSizeSpinBox.setMinimum(3)
        self.fontSizeSpinBox.setMaximum(300)
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fontSizeSpinBox)
        self.showChangeCheck = QtWidgets.QCheckBox(FontDialog)
        self.showChangeCheck.setChecked(True)
        self.showChangeCheck.setObjectName("showChangeCheck")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.showChangeCheck)
        self.buttonBox = QtWidgets.QDialogButtonBox(FontDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.label_2 = QtWidgets.QLabel(FontDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)

        self.retranslateUi(FontDialog)
        self.buttonBox.accepted.connect(FontDialog.accept)
        self.buttonBox.rejected.connect(FontDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FontDialog)

    def retranslateUi(self, FontDialog):
        _translate = QtCore.QCoreApplication.translate
        FontDialog.setWindowTitle(_translate("FontDialog", "Set Font"))
        self.label.setText(_translate("FontDialog", "Family:"))
        self.fontComboBox.setCurrentText(_translate("FontDialog", "Arial"))
        self.fontSizeSpinBox.setSuffix(_translate("FontDialog", "  pt"))
        self.showChangeCheck.setText(_translate("FontDialog", "Show change immediately"))
        self.label_2.setText(_translate("FontDialog", "Size:"))
import resources_rc
