# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logical_rule_listing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogicalRuleListing(object):
    def setupUi(self, LogicalRuleListing):
        LogicalRuleListing.setObjectName("LogicalRuleListing")
        LogicalRuleListing.resize(468, 350)
        self.gridLayout = QtWidgets.QGridLayout(LogicalRuleListing)
        self.gridLayout.setObjectName("gridLayout")
        self.ruleTitleLabel = QtWidgets.QLabel(LogicalRuleListing)
        self.ruleTitleLabel.setObjectName("ruleTitleLabel")
        self.gridLayout.addWidget(self.ruleTitleLabel, 0, 0, 1, 2)
        self.editButton = QtWidgets.QPushButton(LogicalRuleListing)
        self.editButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 0, 2, 1, 1)
        self.removeButton = QtWidgets.QPushButton(LogicalRuleListing)
        self.removeButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(LogicalRuleListing)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(LogicalRuleListing)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.givensScroll = QtWidgets.QScrollArea(LogicalRuleListing)
        self.givensScroll.setWidgetResizable(True)
        self.givensScroll.setObjectName("givensScroll")
        self.givensLayout = QtWidgets.QWidget()
        self.givensLayout.setGeometry(QtCore.QRect(0, 0, 290, 274))
        self.givensLayout.setObjectName("givensLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.givensLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.givensScroll.setWidget(self.givensLayout)
        self.gridLayout.addWidget(self.givensScroll, 2, 0, 1, 1)
        self.resultsScroll = QtWidgets.QScrollArea(LogicalRuleListing)
        self.resultsScroll.setWidgetResizable(True)
        self.resultsScroll.setObjectName("resultsScroll")
        self.resultsLayout = QtWidgets.QWidget()
        self.resultsLayout.setGeometry(QtCore.QRect(0, 0, 150, 274))
        self.resultsLayout.setObjectName("resultsLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.resultsLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultsScroll.setWidget(self.resultsLayout)
        self.gridLayout.addWidget(self.resultsScroll, 2, 1, 1, 3)

        self.retranslateUi(LogicalRuleListing)
        QtCore.QMetaObject.connectSlotsByName(LogicalRuleListing)

    def retranslateUi(self, LogicalRuleListing):
        _translate = QtCore.QCoreApplication.translate
        LogicalRuleListing.setWindowTitle(_translate("LogicalRuleListing", "Form"))
        self.ruleTitleLabel.setText(_translate("LogicalRuleListing", "<html><head/><body><p><span style=\" font-size:16pt;\">Rule Title</span></p></body></html>"))
        self.editButton.setText(_translate("LogicalRuleListing", "Edit"))
        self.removeButton.setText(_translate("LogicalRuleListing", "❌"))
        self.label.setText(_translate("LogicalRuleListing", "Givens"))
        self.label_2.setText(_translate("LogicalRuleListing", "Results"))
