# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library_action_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LibraryActionDialog(object):
    def setupUi(self, LibraryActionDialog):
        LibraryActionDialog.setObjectName("LibraryActionDialog")
        LibraryActionDialog.resize(249, 151)
        self.formLayout = QtWidgets.QFormLayout(LibraryActionDialog)
        self.formLayout.setObjectName("formLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(LibraryActionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.buttonBox)
        self.newDiagramButton = QtWidgets.QPushButton(LibraryActionDialog)
        self.newDiagramButton.setObjectName("newDiagramButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.newDiagramButton)
        self.existingDiagramButton = QtWidgets.QPushButton(LibraryActionDialog)
        self.existingDiagramButton.setObjectName("existingDiagramButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.existingDiagramButton)
        self.externalWebButton = QtWidgets.QPushButton(LibraryActionDialog)
        self.externalWebButton.setObjectName("externalWebButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.externalWebButton)

        self.retranslateUi(LibraryActionDialog)
        self.newDiagramButton.clicked.connect(LibraryActionDialog.accept) # type: ignore
        self.existingDiagramButton.clicked.connect(LibraryActionDialog.accept) # type: ignore
        self.externalWebButton.clicked.connect(LibraryActionDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LibraryActionDialog)

    def retranslateUi(self, LibraryActionDialog):
        _translate = QtCore.QCoreApplication.translate
        LibraryActionDialog.setWindowTitle(_translate("LibraryActionDialog", "Dialog"))
        self.newDiagramButton.setText(_translate("LibraryActionDialog", "Link to a New Diagram"))
        self.existingDiagramButton.setText(_translate("LibraryActionDialog", "Link to an Existing Diagram"))
        self.externalWebButton.setText(_translate("LibraryActionDialog", "Link to an External Web Page"))
