# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logical_rule_listing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogicalRuleListing(object):
    def setupUi(self, LogicalRuleListing):
        LogicalRuleListing.setObjectName("LogicalRuleListing")
        LogicalRuleListing.resize(536, 79)
        self.gridLayout = QtWidgets.QGridLayout(LogicalRuleListing)
        self.gridLayout.setObjectName("gridLayout")
        self.ruleTitleLabel = QtWidgets.QLabel(LogicalRuleListing)
        self.ruleTitleLabel.setObjectName("ruleTitleLabel")
        self.gridLayout.addWidget(self.ruleTitleLabel, 0, 1, 1, 2)
        self.removeButton = QtWidgets.QPushButton(LogicalRuleListing)
        self.removeButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 0, 4, 1, 1)
        self.editButton = QtWidgets.QPushButton(LogicalRuleListing)
        self.editButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 0, 3, 1, 1)
        self.ruleTitleLabel_2 = QtWidgets.QLabel(LogicalRuleListing)
        self.ruleTitleLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ruleTitleLabel_2.setObjectName("ruleTitleLabel_2")
        self.gridLayout.addWidget(self.ruleTitleLabel_2, 0, 0, 1, 1)

        self.retranslateUi(LogicalRuleListing)
        QtCore.QMetaObject.connectSlotsByName(LogicalRuleListing)

    def retranslateUi(self, LogicalRuleListing):
        _translate = QtCore.QCoreApplication.translate
        LogicalRuleListing.setWindowTitle(_translate("LogicalRuleListing", "Form"))
        self.ruleTitleLabel.setText(_translate("LogicalRuleListing", "<html><head/><body><p><span style=\" font-size:16pt;\">Rule Title</span></p></body></html>"))
        self.removeButton.setText(_translate("LogicalRuleListing", "❌"))
        self.editButton.setText(_translate("LogicalRuleListing", "Edit"))
        self.ruleTitleLabel_2.setText(_translate("LogicalRuleListing", "<html><head/><body><p><span style=\" font-size:16pt;\">Logical Rule:</span></p></body></html>"))
