# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logical_rule_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogicalRuleView(object):
    def setupUi(self, LogicalRuleView):
        LogicalRuleView.setObjectName("LogicalRuleView")
        LogicalRuleView.resize(566, 401)
        self.gridLayout = QtWidgets.QGridLayout(LogicalRuleView)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.ruleTitleLabel = QtWidgets.QLabel(LogicalRuleView)
        self.ruleTitleLabel.setObjectName("ruleTitleLabel")
        self.gridLayout.addWidget(self.ruleTitleLabel, 0, 0, 1, 2)
        self.givensScroll = QtWidgets.QScrollArea(LogicalRuleView)
        self.givensScroll.setWidgetResizable(True)
        self.givensScroll.setObjectName("givensScroll")
        self.givensList = QtWidgets.QWidget()
        self.givensList.setGeometry(QtCore.QRect(0, 0, 278, 334))
        self.givensList.setObjectName("givensList")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.givensList)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addGivenButton = QtWidgets.QPushButton(self.givensList)
        self.addGivenButton.setObjectName("addGivenButton")
        self.gridLayout_2.addWidget(self.addGivenButton, 0, 0, 1, 1)
        self.givensScroll.setWidget(self.givensList)
        self.gridLayout.addWidget(self.givensScroll, 2, 0, 1, 1)
        self.resultsScroll = QtWidgets.QScrollArea(LogicalRuleView)
        self.resultsScroll.setWidgetResizable(True)
        self.resultsScroll.setObjectName("resultsScroll")
        self.resultsList = QtWidgets.QWidget()
        self.resultsList.setGeometry(QtCore.QRect(0, 0, 278, 334))
        self.resultsList.setObjectName("resultsList")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.resultsList)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addResultButton = QtWidgets.QPushButton(self.resultsList)
        self.addResultButton.setObjectName("addResultButton")
        self.gridLayout_3.addWidget(self.addResultButton, 0, 0, 1, 1)
        self.resultsScroll.setWidget(self.resultsList)
        self.gridLayout.addWidget(self.resultsScroll, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(LogicalRuleView)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(LogicalRuleView)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)

        self.retranslateUi(LogicalRuleView)
        QtCore.QMetaObject.connectSlotsByName(LogicalRuleView)

    def retranslateUi(self, LogicalRuleView):
        _translate = QtCore.QCoreApplication.translate
        LogicalRuleView.setWindowTitle(_translate("LogicalRuleView", "Form"))
        self.ruleTitleLabel.setText(_translate("LogicalRuleView", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Logical Diagram Rule</span></p></body></html>"))
        self.addGivenButton.setText(_translate("LogicalRuleView", "Add Given"))
        self.addResultButton.setText(_translate("LogicalRuleView", "Add Result"))
        self.label_2.setText(_translate("LogicalRuleView", "Results"))
        self.label.setText(_translate("LogicalRuleView", "Givens"))
