# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proof_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProofView(object):
    def setupUi(self, ProofView):
        ProofView.setObjectName("ProofView")
        ProofView.resize(386, 367)
        self.gridLayout = QtWidgets.QGridLayout(ProofView)
        self.gridLayout.setObjectName("gridLayout")
        self.proofQEDButton = QtWidgets.QPushButton(ProofView)
        self.proofQEDButton.setObjectName("proofQEDButton")
        self.gridLayout.addWidget(self.proofQEDButton, 1, 3, 1, 1)
        self.gotoStatementButton = QtWidgets.QPushButton(ProofView)
        self.gotoStatementButton.setObjectName("gotoStatementButton")
        self.gridLayout.addWidget(self.gotoStatementButton, 1, 0, 1, 1)
        self.proofStepScroll = QtWidgets.QScrollArea(ProofView)
        self.proofStepScroll.setWidgetResizable(True)
        self.proofStepScroll.setObjectName("proofStepScroll")
        self.proofStepLayout = QtWidgets.QWidget()
        self.proofStepLayout.setGeometry(QtCore.QRect(0, 0, 366, 317))
        self.proofStepLayout.setObjectName("proofStepLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.proofStepLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addProofStepButton = QtWidgets.QPushButton(self.proofStepLayout)
        self.addProofStepButton.setObjectName("addProofStepButton")
        self.verticalLayout.addWidget(self.addProofStepButton)
        self.proofStepScroll.setWidget(self.proofStepLayout)
        self.gridLayout.addWidget(self.proofStepScroll, 0, 0, 1, 4)
        self.loadGivensButton = QtWidgets.QPushButton(ProofView)
        self.loadGivensButton.setObjectName("loadGivensButton")
        self.gridLayout.addWidget(self.loadGivensButton, 1, 1, 1, 1)

        self.retranslateUi(ProofView)
        QtCore.QMetaObject.connectSlotsByName(ProofView)

    def retranslateUi(self, ProofView):
        _translate = QtCore.QCoreApplication.translate
        ProofView.setWindowTitle(_translate("ProofView", "Form"))
        self.proofQEDButton.setText(_translate("ProofView", "QED"))
        self.gotoStatementButton.setText(_translate("ProofView", "Statement"))
        self.addProofStepButton.setText(_translate("ProofView", "Add Proof Step"))
        self.loadGivensButton.setText(_translate("ProofView", "Load Givens"))
