# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proof_step.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProofStep(object):
    def setupUi(self, ProofStep):
        ProofStep.setObjectName("ProofStep")
        ProofStep.resize(447, 607)
        self.gridLayout = QtWidgets.QGridLayout(ProofStep)
        self.gridLayout.setObjectName("gridLayout")
        self.englishText = QtWidgets.QPlainTextEdit(ProofStep)
        self.englishText.setReadOnly(True)
        self.englishText.setObjectName("englishText")
        self.gridLayout.addWidget(self.englishText, 2, 0, 1, 1)
        self.removeButton = QtWidgets.QPushButton(ProofStep)
        self.removeButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 0, 0, 1, 1)

        self.retranslateUi(ProofStep)
        QtCore.QMetaObject.connectSlotsByName(ProofStep)

    def retranslateUi(self, ProofStep):
        _translate = QtCore.QCoreApplication.translate
        ProofStep.setWindowTitle(_translate("ProofStep", "Form"))
        self.englishText.setPlaceholderText(_translate("ProofStep", "English"))
        self.removeButton.setText(_translate("ProofStep", "❌"))
