# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_definition_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetDefinitionDialog(object):
    def setupUi(self, SetDefinitionDialog):
        SetDefinitionDialog.setObjectName("SetDefinitionDialog")
        SetDefinitionDialog.resize(473, 102)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/galaxy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SetDefinitionDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SetDefinitionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.internalLinkRadio = QtWidgets.QRadioButton(SetDefinitionDialog)
        self.internalLinkRadio.setChecked(True)
        self.internalLinkRadio.setObjectName("internalLinkRadio")
        self.gridLayout.addWidget(self.internalLinkRadio, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(SetDefinitionDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.externalLinkRadio = QtWidgets.QRadioButton(SetDefinitionDialog)
        self.externalLinkRadio.setObjectName("externalLinkRadio")
        self.gridLayout.addWidget(self.externalLinkRadio, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetDefinitionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 3)
        self.externalUrlLine = QtWidgets.QLineEdit(SetDefinitionDialog)
        self.externalUrlLine.setEnabled(False)
        self.externalUrlLine.setObjectName("externalUrlLine")
        self.gridLayout.addWidget(self.externalUrlLine, 1, 1, 1, 1)
        self.externalLinkTextLine = QtWidgets.QLineEdit(SetDefinitionDialog)
        self.externalLinkTextLine.setEnabled(False)
        self.externalLinkTextLine.setObjectName("externalLinkTextLine")
        self.gridLayout.addWidget(self.externalLinkTextLine, 1, 2, 1, 1)

        self.retranslateUi(SetDefinitionDialog)
        self.buttonBox.accepted.connect(SetDefinitionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SetDefinitionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetDefinitionDialog)

    def retranslateUi(self, SetDefinitionDialog):
        _translate = QtCore.QCoreApplication.translate
        SetDefinitionDialog.setWindowTitle(_translate("SetDefinitionDialog", "Set Definition"))
        self.internalLinkRadio.setText(_translate("SetDefinitionDialog", "Internal Link"))
        self.label.setText(_translate("SetDefinitionDialog", "Navigate to the diagram that is the definition then right-click its tab."))
        self.externalLinkRadio.setText(_translate("SetDefinitionDialog", "External Link"))
        self.externalUrlLine.setPlaceholderText(_translate("SetDefinitionDialog", "e.g. \"https://en.wikipedia.org/wiki/Category_(mathematics)\""))
        self.externalLinkTextLine.setPlaceholderText(_translate("SetDefinitionDialog", "e.g. \"Category Theory\""))
import resources_rc
