# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_definition_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetDefinitionDialog(object):
    def setupUi(self, SetDefinitionDialog):
        SetDefinitionDialog.setObjectName("SetDefinitionDialog")
        SetDefinitionDialog.resize(447, 116)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/galaxy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SetDefinitionDialog.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(SetDefinitionDialog)
        self.formLayout.setObjectName("formLayout")
        self.internalLinkRadio = QtWidgets.QRadioButton(SetDefinitionDialog)
        self.internalLinkRadio.setChecked(True)
        self.internalLinkRadio.setObjectName("internalLinkRadio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.internalLinkRadio)
        self.label = QtWidgets.QLabel(SetDefinitionDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.externalLinkRadio = QtWidgets.QRadioButton(SetDefinitionDialog)
        self.externalLinkRadio.setObjectName("externalLinkRadio")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.externalLinkRadio)
        self.externalUrlLine = QtWidgets.QLineEdit(SetDefinitionDialog)
        self.externalUrlLine.setObjectName("externalUrlLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.externalUrlLine)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetDefinitionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(SetDefinitionDialog)
        self.buttonBox.accepted.connect(SetDefinitionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SetDefinitionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetDefinitionDialog)

    def retranslateUi(self, SetDefinitionDialog):
        _translate = QtCore.QCoreApplication.translate
        SetDefinitionDialog.setWindowTitle(_translate("SetDefinitionDialog", "Set Definition"))
        self.internalLinkRadio.setText(_translate("SetDefinitionDialog", "Internal Link"))
        self.label.setText(_translate("SetDefinitionDialog", "Navigate to the diagram that is the definition then click OK."))
        self.externalLinkRadio.setText(_translate("SetDefinitionDialog", "External Link"))
        self.externalUrlLine.setPlaceholderText(_translate("SetDefinitionDialog", "e.g. \"https://en.wikipedia.org/wiki/Category_(mathematics)\""))
import resources_rc
